import { z } from 'zod';
import type { App } from '../app/composition.js';
import type { ModelProvider } from '../shared/ports.js';
import { newId, CreateToolIntegrationArgsSchema, type Conversation, type ConversationMessage, type ConversationProposal, type ConversationSeed, type ToolTrace } from '../domain/index.js';
import { ToolRegistry, type AgentTool, type ToolResult } from '../agent/tool.js';
import { PermissionEngine } from '../agent/permissions.js';
import { SessionTelemetry } from '../agent/telemetry.js';
import { runAgentLoop, type AgentLoopStatus } from '../agent/loop.js';
import type { AgentEventSink, ReceiptSink } from '../agent/protocol.js';

/**
 * Resident agent turn (PROPOSAL-resident-agent R1/R2): one conversation reply
 * generated by the REAL agent kernel (tool-using loop) — not a single blind
 * structured call. The agent can inspect the whole workspace through read
 * tools (runs / hypotheses / evidence / plans / search / status) and propose
 * actions; proposals NEVER execute inside the loop — they persist as pending
 * cards resolved by the researcher (or by a remembered per-conversation
 * grant) after the turn lands. Receipt discipline follows the conversation
 * doc: full provenance receipts stay run-scoped; here every model call is
 * AGGREGATED into the message usage summary (provider/model/tokens/counts).
 */

export const ConversationAgentReplySchema = z.object({
  reply: z.string().min(1),
  clarifyingQuestions: z.array(z.string().min(1).max(500)).max(3),
  candidates: z.array(z.object({
    text: z.string().min(1).max(2000),
    rationale: z.string().min(1).max(2000),
  })).max(5),
  readyToConverge: z.boolean(),
});
export type ConversationAgentReply = z.infer<typeof ConversationAgentReplySchema>;

/** Args contracts for the proposable action kinds (validated before a card is created). */
export const LaunchResearchArgsSchema = z.object({ question: z.string().min(10).max(2000) });
export const CreateAutomationArgsSchema = z.object({
  label: z.string().min(1).max(120).optional(),
  trigger: z.discriminatedUnion('kind', [
    z.object({ kind: z.literal('run_completed') }),
    z.object({ kind: z.literal('schedule'), intervalMinutes: z.number().int().min(1).max(20160) }),
  ]),
  task: z.string().min(10).max(2000),
});
export const CancelAutomationArgsSchema = z.object({ automationId: z.string().regex(/^auto_[a-z0-9]+$/) });

// TIS T4: tool-config drafting args live with the tool-integration domain
// (single owner); re-exported here so action-arg imports stay one-sided.
export { CreateToolIntegrationArgsSchema };

const ACTION_ARG_SCHEMAS = {
  launch_research: LaunchResearchArgsSchema,
  create_automation: CreateAutomationArgsSchema,
  cancel_automation: CancelAutomationArgsSchema,
  create_tool_integration: CreateToolIntegrationArgsSchema,
} as const;
export type ProposalKind = keyof typeof ACTION_ARG_SCHEMAS;

export interface ConversationTurnInput {
  /** The researcher's new message, or (source='automation') the trigger notice text. */
  text: string;
  seeds: ConversationSeed[];
  /** Transcript window chosen by the caller (token budget control). */
  history: ConversationMessage[];
  source: 'researcher' | 'automation';
  /** Turn ceiling for the kernel loop (default 8; automations pass their own cap). */
  maxTurns?: number;
  /**
   * Reasoning effort for this turn's model calls, resolved by the CALLER
   * (conversations.ts effectiveConversationReasoning — kept out of this module to
   * avoid an import cycle). Absent/undefined = nothing is sent on the wire.
   */
  reasoning?: { style: 'reasoning_effort' | 'enable_thinking' | 'thinking_budget'; gear: 'low' | 'medium' | 'high' };
}

export interface ConversationTurnUsage {
  provider: string;
  modelId: string;
  latencyMs: number;
  inputTokens?: number;
  outputTokens?: number;
  modelCalls: number;
  toolCalls: number;
}

export interface ConversationTurnGeneration {
  status: AgentLoopStatus;
  reply?: ConversationAgentReply;
  toolTrace: ToolTrace[];
  usage?: ConversationTurnUsage;
  proposals: ConversationProposal[];
  error?: string;
}

const head = (s: string, n: number): string => (s.length <= n ? s : `${s.slice(0, n)}…`);

const RESIDENT_SYSTEM_PROMPT = `你是 FAR-Lab 研究工作区的常驻 Agent——研究者通过对话与你讨论这个工作区的任何内容、向你布置工作。你运行在带工具的循环里：每一轮要么调用一个工具，要么给出最终回复。

职责与行为：
- 全域视野：用工具核实工作区事实（runs/假设/证据/计划/检索/状态），绝不在没有工具结果支撑时编造工作区内容、数字或文献。工具空结果是诚实发现，如实报告，不要换着花样重复查询。
- 研究前引导：当研究者还在塑形研究问题时，像敏锐的同行一样追问模糊概念、要求澄清变量与机制、指出被忽略的角度与对立解释，主动给出不同方向的候选问题（candidates）。
- 研究后讨论：run 已存在时，先读它的假设/证据/计划再评论；指出证据缺口、反例方向、下一步该做什么。
- 行动提案：研究者要求做事（启动研究、建自动化、停自动化、接入工具）时，用 propose_action 提案——它会生成一张需要研究者批准的卡片；本对话已记住"不再询问"的种类会在回合结束后自动执行。不要重复提案已经在等待批准的同类行动。研究者想接入外部工具（MCP 服务器、技能、命令、钩子规则）时，用 create_tool_integration 起草配置并说明理由与注意事项（如需要安装的依赖、密钥要研究者自己填）；起草的配置一律以停用状态入库，由研究者在设置中审查启用。
- 材料优先：研究者提供的文献/材料是唯一可引用的文献事实来源——绝不允许编造文献、数据或结论；没有材料或工具支撑的推断要明确标注"待验证"。
- 诚实：不知道就说不确定；工具失败就如实说明。用研究者的语言回复（中文提问则中文）。
- 精炼：每轮最终回复一般不超过 300 字，像对话而不是报告；讨论足够聚焦或研究者要求时才给 candidates 并把 readyToConverge 设为 true。

最终回复契约（finish 的 result 字段）：
{"reply": "<给研究者看的回复（markdown，可含简短列表）>", "clarifyingQuestions": ["<最多3个本轮追问，可空数组>"], "candidates": [{"text": "<候选研究问题，一句可检验的问句>", "rationale": "<为何值得做：已知/未知/价值>"], "readyToConverge": true|false}`;

// ---- read tools: the agent's eyes on the workspace (all local store reads) ----

const makeListRuns = (app: App): AgentTool => ({
  name: 'list_runs',
  description: 'List research runs in this workspace (newest first): id, status, current stage, creation time, and the research question.',
  inputSchema: z.object({ limit: z.number().int().min(1).max(30).default(10) }),
  riskClass: 'read',
  async execute(args): Promise<ToolResult> {
    const { limit } = z.object({ limit: z.number().int().min(1).max(30).default(10) }).parse(args);
    const rows = app.store.listRuns(limit).map((r) => {
      const run = app.store.getRun(r.id);
      const question = run !== null ? app.store.getObject('question', run.questionId) : null;
      return {
        id: r.id, status: r.status, currentStage: r.currentStage, createdAt: r.createdAt,
        question: question !== null ? head(question.text, 160) : null,
      };
    });
    return { ok: true, data: { runs: rows }, summary: `${rows.length} runs` };
  },
});

const makeGetRunDetails = (app: App): AgentTool => ({
  name: 'get_run_details',
  description: 'One run\'s real state: question, stage progression, hypothesis/evidence/source counts, top hypotheses with their claim balance, revision and experiment counts.',
  inputSchema: z.object({ runId: z.string().min(1).max(64) }),
  riskClass: 'read',
  async execute(args): Promise<ToolResult> {
    const { runId } = z.object({ runId: z.string().min(1).max(64) }).parse(args);
    const run = app.store.getRun(runId);
    if (run === null) return { ok: false, error: { kind: 'validation', message: `run not found: ${runId}` } };
    const question = app.store.getObject('question', run.questionId);
    const hypotheses = app.store.listObjects('hypothesis', runId);
    const claims = app.store.listObjects('claim', runId);
    const relations = app.store.listObjects('evidence_relation', runId);
    const sources = app.store.listObjects('source_document', runId);
    return {
      ok: true,
      data: {
        id: run.id, status: run.status, currentStage: run.currentStage,
        createdAt: run.createdAt, updatedAt: run.updatedAt,
        question: question !== null ? head(question.text, 300) : null,
        stages: run.stages.map((s) => ({ stage: s.stage, state: s.state })),
        counts: {
          hypotheses: hypotheses.length, claims: claims.length,
          evidenceRelations: relations.length, sourceDocuments: sources.length,
          revisions: app.store.listObjects('revision', runId).length,
          experimentRuns: app.store.listObjects('experiment_run', runId).length,
        },
        topHypotheses: hypotheses.slice(0, 5).map((h) => ({
          id: h.id, statement: head(h.statement, 200), mechanism: head(h.mechanism, 120),
          supportingClaims: h.supportingClaimIds.length, counterClaims: h.counterClaimIds.length,
        })),
      },
      summary: `run ${run.id.slice(0, 10)} ${run.status}`,
    };
  },
});

const makeGetRunPlan = (app: App): AgentTool => ({
  name: 'get_run_plan',
  description: 'The run\'s latest research plan (goal, stages, key actions) as a bounded excerpt. An absent plan is an honest finding.',
  inputSchema: z.object({ runId: z.string().min(1).max(64) }),
  riskClass: 'read',
  summarize: (payload) => {
    const p = payload as { plan?: unknown; note?: string };
    return p.plan !== null && p.plan !== undefined ? 'plan excerpt' : String(p.note ?? 'no plan');
  },
  async execute(args): Promise<ToolResult> {
    const { runId } = z.object({ runId: z.string().min(1).max(64) }).parse(args);
    if (app.store.getRun(runId) === null) return { ok: false, error: { kind: 'validation', message: `run not found: ${runId}` } };
    const plan = app.store.listObjects('plan', runId).at(-1) ?? null;
    if (plan === null) return { ok: true, data: { plan: null, note: 'this run has no plan yet (still early-stage or not generated)' }, summary: 'no plan' };
    const serialized = JSON.stringify(plan);
    return {
      ok: true,
      data: { planId: plan.id, excerpt: serialized.slice(0, 4000), truncated: serialized.length > 4000 },
      summary: `plan ${plan.id.slice(0, 10)}`,
    };
  },
});

const makeSearchWorkspace = (app: App): AgentTool => ({
  name: 'search_workspace',
  description: 'Full-text search across this workspace\'s research questions, hypotheses and claims (bm25-ranked, CJK-aware). Empty results are honest findings.',
  inputSchema: z.object({ query: z.string().min(2).max(200) }),
  riskClass: 'read',
  async execute(args): Promise<ToolResult> {
    const { query } = z.object({ query: z.string().min(2).max(200) }).parse(args);
    const hits = app.store.searchText(query, { questions: 5, hypotheses: 8, claims: 8 });
    const trim = (rows: typeof hits.questions) => rows.map((h) => ({ runId: h.runId, id: h.id, text: head(h.text, 200) }));
    return {
      ok: true,
      data: { questions: trim(hits.questions), hypotheses: trim(hits.hypotheses), claims: trim(hits.claims) },
      summary: `${hits.questions.length + hits.hypotheses.length + hits.claims.length} hits`,
    };
  },
});

const makeWorkspaceStatus = (app: App): AgentTool => ({
  name: 'workspace_status',
  description: 'Workspace overview: run counts by status, in-flight runs with current stage, conversation count, enabled automations, and the active model config id.',
  inputSchema: z.object({}),
  riskClass: 'read',
  async execute(): Promise<ToolResult> {
    const runs = app.store.listRuns(200);
    const byStatus: Record<string, number> = {};
    for (const r of runs) byStatus[r.status] = (byStatus[r.status] ?? 0) + 1;
    const automations = app.store.listObjects('automation', '__none__');
    const activeModel = app.store.getMeta('active_model_config');
    return {
      ok: true,
      data: {
        runsTotal: runs.length,
        runsByStatus: byStatus,
        inFlight: runs.filter((r) => r.status === 'running' || r.status === 'queued')
          .slice(0, 10).map((r) => ({ id: r.id, stage: r.currentStage })),
        conversations: app.store.listObjects('conversation', '__none__').length,
        automations: { total: automations.length, enabled: automations.filter((a) => a.enabled).length },
        activeModelConfigId: activeModel,
      },
      summary: `${runs.length} runs`,
    };
  },
});

// ---- propose_action: records a pending approval card; NEVER executes in-loop ----

const seedDigest = (seeds: readonly ConversationSeed[] | undefined): string[] =>
  (seeds ?? []).slice(0, 12).map((s) => {
    const ident = s.identifiers[0];
    return `- ${s.title}${s.year !== undefined ? ` (${s.year})` : ''}${ident !== undefined ? ` [${ident.kind}:${ident.value}]` : ''}${s.text !== undefined ? ` · 全文已提供(${s.text.length}字符)` : ''}`;
  });

const makeProposeAction = (app: App, conv: Conversation, proposals: ConversationProposal[]): AgentTool => ({
  name: 'propose_action',
  description: 'Propose a concrete action as an approval card for the researcher: launch_research (start a run carrying ALL conversation materials), create_automation (standing agent task on schedule or on run completion), cancel_automation, create_tool_integration (stage a tool config — MCP server / skill / command / hook rule — from a draft; stored DISABLED, the researcher activates it in settings). Records the proposal — execution happens only after approval.',
  inputSchema: z.object({
    kind: z.enum(['launch_research', 'create_automation', 'cancel_automation', 'create_tool_integration']),
    title: z.string().min(1).max(300),
    args: z.record(z.string(), z.unknown()),
  }),
  riskClass: 'read', // records a card only; execution is researcher-gated outside the loop
  async execute(args): Promise<ToolResult> {
    const parsed = z.object({
      kind: z.enum(['launch_research', 'create_automation', 'cancel_automation', 'create_tool_integration']),
      title: z.string().min(1).max(300),
      args: z.record(z.string(), z.unknown()),
    }).parse(args);
    if (proposals.length >= 10) {
      return { ok: false, error: { kind: 'validation', message: 'this turn already holds 10 proposals — finish and let the researcher resolve them first' } };
    }
    const argCheck = ACTION_ARG_SCHEMAS[parsed.kind].safeParse(parsed.args);
    if (!argCheck.success) {
      return { ok: false, error: { kind: 'validation', message: `invalid args for ${parsed.kind}: ${argCheck.error.issues.map((i) => `${i.path.join('.') || '(root)'}: ${i.message}`).slice(0, 3).join('; ')}` } };
    }
    if (parsed.kind === 'cancel_automation') {
      const cancel = CancelAutomationArgsSchema.parse(parsed.args);
      const target = app.store.getObject('automation', cancel.automationId);
      if (target === null) return { ok: false, error: { kind: 'validation', message: `automation not found: ${cancel.automationId}` } };
      if (target.conversationId !== conv.id) return { ok: false, error: { kind: 'validation', message: 'that automation belongs to a different conversation' } };
    }
    const autoApproved = conv.autoApprove.includes(parsed.kind);
    // RU-3 T6: server-computed disclosure — the model cannot forge risk level
    // or arg rendering; the card's title stays explicitly model-authored.
    const RISK_BY_KIND: Record<typeof parsed.kind, 'low' | 'moderate' | 'high'> = {
      launch_research: 'moderate',
      create_automation: 'moderate',
      cancel_automation: 'low',
      create_tool_integration: 'high',
    };
    const renderArgs = (kind: typeof parsed.kind, a: Record<string, unknown>): Record<string, string> => {
      const s = (v: unknown, max = 160): string => String(v ?? '').slice(0, max);
      switch (kind) {
        case 'launch_research':
          return { question: s(a.question), seeds: s((a.seedTexts as unknown[] | undefined)?.length ?? 0) };
        case 'create_automation':
          return { task: s(a.task), trigger: s(a.schedule ?? a.onRunCompleted) };
        case 'cancel_automation':
          return { automationId: s(a.automationId) };
        case 'create_tool_integration':
          return { toolType: s((a.draft as { toolType?: string } | undefined)?.toolType), label: s((a.draft as { label?: string } | undefined)?.label) };
      }
    };
    const proposal: ConversationProposal = {
      id: newId('act'),
      kind: parsed.kind,
      title: parsed.title,
      args: argCheck.data as Record<string, unknown>,
      status: 'pending',
      riskLevel: RISK_BY_KIND[parsed.kind],
      argSummary: renderArgs(parsed.kind, argCheck.data as Record<string, unknown>),
      ...(autoApproved ? { autoApproved: true } : {}),
      createdAt: new Date().toISOString(),
    };
    proposals.push(proposal);
    return {
      ok: true,
      data: {
        proposalId: proposal.id,
        state: autoApproved
          ? 'pre-approved for this conversation (remembered grant) — will execute when this turn completes'
          : 'awaiting researcher approval — tell the researcher what you proposed and why',
      },
      summary: `proposed ${parsed.kind}`,
    };
  },
});

// ---- the turn ----

/**
 * R2-13 F-5 fix: the conversation kernel's allow-expansion is keyed on the
 * registry's own risk class, not on registry membership. Read-class tools pass
 * (including propose_action — it only records an approval card; execution is
 * researcher-gated outside the loop). Anything else — an execute/edit-class
 * tool registered by a future kernel evolution — gets NO allow rule and falls
 * to the engine's fail-closed default instead of silently inheriting one.
 */
export const conversationAllowRules = (tools: ToolRegistry): Array<{ tool: string; effect: 'allow' }> =>
  tools.names()
    .filter((name) => tools.get(name)?.riskClass === 'read')
    .map((name) => ({ tool: name, effect: 'allow' as const }));

export async function generateConversationTurn(
  app: App,
  provider: ModelProvider,
  conv: Conversation,
  input: ConversationTurnInput,
): Promise<ConversationTurnGeneration> {
  const proposals: ConversationProposal[] = [];
  const toolTrace: ToolTrace[] = [];
  const tools = new ToolRegistry()
    .register(makeListRuns(app))
    .register(makeGetRunDetails(app))
    .register(makeGetRunPlan(app))
    .register(makeSearchWorkspace(app))
    .register(makeWorkspaceStatus(app))
    .register(makeProposeAction(app, conv, proposals));
  const permissions = new PermissionEngine({
    rules: conversationAllowRules(tools),
    defaultEffect: 'deny',
  });

  // Aggregating receipt collector (documented decision: conversation turns keep
  // usage on the message; full provenance receipts start when a run is launched).
  let usageModelCalls = 0;
  let usageLatencyMs = 0;
  let usagePromptTokens = 0;
  let usageCompletionTokens = 0;
  let sawTokens = false;
  let lastProvider = provider.name;
  let lastModelId = 'unknown';
  const recordReceipt: ReceiptSink = (partial) => {
    if (partial.kind !== 'model_call' || partial.modelCall === undefined) return;
    const mc = partial.modelCall;
    usageModelCalls += 1;
    usageLatencyMs += mc.latencyMs;
    lastProvider = mc.provider;
    lastModelId = mc.modelId;
    if (mc.usage.promptTokens !== undefined || mc.usage.completionTokens !== undefined) {
      sawTokens = true;
      usagePromptTokens += mc.usage.promptTokens ?? 0;
      usageCompletionTokens += mc.usage.completionTokens ?? 0;
    }
  };

  const emit: AgentEventSink = (ev) => {
    if (ev.type === 'tool_used') {
      toolTrace.push({
        tool: ev.tool, ok: ev.ok,
        ...(ev.summary !== undefined ? { summary: ev.summary.slice(0, 300) } : {}),
        durationMs: ev.durationMs,
      });
    }
  };

  const telemetry = new SessionTelemetry();
  const history = input.history;
  const materials = history
    .filter((m) => m.role === 'researcher' && (m.seeds?.length ?? 0) > 0)
    .flatMap((m) => seedDigest(m.seeds));
  const priorCandidates = history
    .filter((m) => m.role === 'agent' && (m.candidates?.length ?? 0) > 0)
    .flatMap((m) => (m.candidates ?? []).map((c) => `- ${c.text}`));
  const pendingProposals = history
    .flatMap((m) => m.proposals ?? [])
    .filter((p) => p.status === 'pending')
    .map((p) => `- ${p.kind}: ${p.title}`);
  const launchedRuns = conv.runIds.length > 0
    ? conv.runIds.slice(-10).map((id) => {
      const run = app.store.getRun(id);
      return run === null ? `- ${id} (not found)` : `- ${id} ${run.status} @ ${run.currentStage}`;
    })
    : [];

  const task = input.source === 'researcher'
    ? `研究者发来新消息：「${input.text}」\n回应它——需要工作区事实时先用工具核实，需要行动时用 propose_action 提案，然后 finish 给出最终回复。`
    : input.text; // automation trigger notice already carries its task

  const res = await runAgentLoop(
    {
      capability: 'conversation-resident',
      systemPrompt: RESIDENT_SYSTEM_PROMPT,
      task,
      maxTurns: input.maxTurns ?? 8,
      resultSchema: ConversationAgentReplySchema,
      contextEntries: [
        {
          label: 'conversation',
          payload: {
            id: conv.id, title: conv.title, status: conv.status,
            rememberedAutoApprove: conv.autoApprove.length > 0 ? conv.autoApprove : '（无——所有行动都需要批准）',
            launchedRuns: launchedRuns.length > 0 ? launchedRuns : '（本对话尚未启动研究）',
          },
        },
        {
          label: 'transcript_window',
          payload: history.map((m) => ({
            role: m.role,
            text: head(m.content, 1200),
            ...(m.candidates !== undefined && m.candidates.length > 0 ? { proposedCandidates: m.candidates.map((c) => c.text) } : {}),
            ...(m.proposals !== undefined && m.proposals.length > 0 ? { proposalsThisTurn: m.proposals.map((p) => `${p.kind}(${p.status})`) } : {}),
          })),
        },
        { label: 'materials_provided', payload: materials.length > 0 ? materials : '（研究者尚未提供材料）' },
        { label: 'prior_candidate_questions', payload: priorCandidates.length > 0 ? priorCandidates : '（尚未提出候选问题）' },
        { label: 'proposals_awaiting_approval', payload: pendingProposals.length > 0 ? pendingProposals : '（无等待中的提案）' },
        ...(input.seeds.length > 0 ? [{ label: 'new_materials', payload: seedDigest(input.seeds) }] : []),
      ],
    },
    {
      provider,
      tools,
      permissions,
      sessionId: newId('ags'),
      purpose: 'conversation:turn',
      ...(input.reasoning !== undefined ? { reasoning: input.reasoning } : {}),
      emit,
      recordReceipt,
      telemetry,
    },
  );

  const tel = telemetry.summary();
  const usage: ConversationTurnUsage | undefined = usageModelCalls > 0 ? {
    provider: lastProvider,
    modelId: lastModelId,
    latencyMs: usageLatencyMs,
    modelCalls: usageModelCalls,
    toolCalls: tel.toolCalls,
    ...(sawTokens ? { inputTokens: usagePromptTokens, outputTokens: usageCompletionTokens } : {}),
  } : undefined;

  return {
    status: res.status,
    ...(res.status === 'completed' && res.result !== undefined
      ? { reply: ConversationAgentReplySchema.parse(res.result) }
      : { error: res.error ?? `agent loop ended with status ${res.status}` }),
    toolTrace,
    ...(usage !== undefined ? { usage } : {}),
    proposals,
  };
}
