/**
 * tests/discovery/strategies/data_driven.test.ts — contract + applicability +
 * offline end-to-end for the data-driven strategy (numeric-pattern →
 * generative mechanism, with the correlation-is-not-causation guardrail).
 *
 * Applicability note: the demo corpus abstracts contain NO digits, so the
 * full demo corpus exercises the SKIP branch; a hand-built digit-bearing
 * abstract exercises the APPLIES branch.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { dataDrivenStrategy } from '../../../src/discovery/strategies/data_driven.ts';
import { buildStrategyMessages } from '../../../src/discovery/strategies/strategy.ts';
import { makeCandidate, makeFullCorpus, runStrategyOffline } from './helpers.ts';
import { createCorpusSnapshot } from '../../../src/retrieval/corpus.ts';
import { computeDocumentId } from '../../../src/retrieval/hash.ts';
import { RESEARCH_DEMO_DOCS } from '../../../src/research/research_fixtures.ts';
import type { RetrievedDocument } from '../../../src/retrieval/types.ts';

/** A demo-document copy whose abstract reports numbers (digit-bearing). */
const numericAbstractDoc: RetrievedDocument = {
  ...RESEARCH_DEMO_DOCS[0]!,
  documentId: computeDocumentId('openalex', 'W-demo-numeric'),
  abstract:
    'Across 42 systems the radius anomaly scales with insolation flux (slope 0.08 per unit flux, r = 0.7).',
};

describe('data_driven strategy (contract)', () => {
  it('system prompt carries the strategy identity, signature, and BOTH structural markers', () => {
    const messages = buildStrategyMessages(dataDrivenStrategy, {
      question: 'q',
      corpusAllowlist: '(allowlist)',
      perCallTarget: 2,
    });
    const system = messages[0]!.content;
    assert.ok(system.includes('data_driven'));
    assert.ok(system.includes(dataDrivenStrategy.signature));
    for (const marker of dataDrivenStrategy.requiredMarkers) {
      assert.ok(system.includes(marker), `system prompt must demand ${marker}`);
    }
    // The correlation-is-not-causation guardrail is the strategy's differentiator.
    assert.ok(system.includes('Correlation is not causation'));
  });

  it('shared rules (threshold coherence + citation allowlist) are present', () => {
    const system = buildStrategyMessages(dataDrivenStrategy, {
      question: 'q',
      corpusAllowlist: '(allowlist)',
      perCallTarget: 1,
    })[0]!.content;
    assert.ok(system.includes('falsificationMethod'));
    assert.ok(system.includes('CITATION RULE'));
  });
});

describe('data_driven strategy (applicability — honest skip)', () => {
  it('skips with a reason when no corpus abstract contains a digit (v0 numeric heuristic)', () => {
    // The demo corpus abstracts are pure prose — no reported numbers to explain.
    const verdict = dataDrivenStrategy.evaluateApplicability({
      question: 'q',
      corpus: makeFullCorpus(),
    });
    assert.equal(verdict.applicable, false);
    assert.match(verdict.skipReason ?? '', /needs at least one corpus abstract reporting numeric patterns/);
  });

  it('applies when at least one corpus abstract reports numeric patterns', () => {
    const verdict = dataDrivenStrategy.evaluateApplicability({
      question: 'q',
      corpus: createCorpusSnapshot([numericAbstractDoc], ['numeric query'], '2026-08-15T00:00:00.000Z'),
    });
    assert.deepEqual(verdict, { applicable: true, skipReason: null });
  });
});

describe('data_driven strategy (offline end-to-end via the fixture seam)', () => {
  it('parses a pattern→mechanism candidate with both markers through discovery_data_driven', async () => {
    const result = await runStrategyOffline(dataDrivenStrategy, {
      hypotheses: [
        makeCandidate({
          statement:
            'The reported radius-anomaly–insolation scaling is generated by irradiation-delayed contraction of the planetary envelope.',
          mechanism:
            'EMPIRICAL_PATTERN: radius anomaly scales with insolation (slope 0.08 per unit flux, r = 0.7, 42 systems) [doc-1]; ' +
            'MECHANISM_EXPLANATION: deposited irradiation energy delays cooling and contraction of the envelope, generating the observed flux scaling.',
          falsificationMethod: {
            prediction:
              'Intervening on the cause (age/insolation matched pairs with different flux histories) changes the anomaly beyond what re-measuring the correlation shows.',
            metric: 'matched-pair anomaly difference (sigma)',
            comparator: 'gt',
            value: 1.5,
          },
        }),
      ],
    });
    assert.equal(result.hypotheses.length, 1);
    const mechanism = result.hypotheses[0]!.mechanism as string;
    assert.ok(mechanism.includes('EMPIRICAL_PATTERN:'));
    assert.ok(mechanism.includes('MECHANISM_EXPLANATION:'));
  });
});
