/**
 * Static shell completion generation (B11 CLI maturity — R2 of PLAN-reuse-adoption).
 * FAR_COMMANDS mirrors the router in main.ts: it is the single source of truth the
 * generators below walk, so a command added to the router must be added here too
 * (and to HELP) or it will not complete.
 */

export interface CompletionCommand {
  readonly name: string;
  readonly help: string;
  readonly subs: readonly { readonly name: string; readonly help: string }[];
}

/** The real command tree as dispatched by src/cli/main.ts (completion truth). */
export const FAR_COMMANDS: readonly CompletionCommand[] = [
  {
    name: 'research',
    help: 'run the research pipeline',
    subs: [
      { name: 'start', help: 'create and execute a research run' },
      { name: 'status', help: 'show run status/stages/progress' },
      { name: 'inspect', help: 'inspect run objects' },
      { name: 'cancel', help: 'request run cancellation' },
      { name: 'resume', help: 'resume a partial/failed run' },
      { name: 'export', help: 'export report or bundle' },
      { name: 'feedback', help: 'record feedback on a run' },
      { name: 'counter-search', help: 'run one counter-evidence search into the corpus' },
      { name: 'lineage', help: 'trajectory graph (revisions/hypotheses/evidence)' },
      { name: 'supervise', help: 'live supervisor analysis with action hints' },
      { name: 'fork', help: 'branch a settled run (alternative direction)' },
    ],
  },
  { name: 'runs', help: 'list research runs', subs: [] },
  {
    name: 'experiment',
    help: 'durable experiment scheduler',
    subs: [
      { name: 'run', help: 'execute an ExperimentSpec now' },
      { name: 'enqueue', help: 'queue an ExperimentSpec' },
      { name: 'simulate', help: 'execute a SimulationSpec (CRN/simulator)' },
      { name: 'worker', help: 'drain queued experiments' },
      { name: 'status', help: 'job and experiment truth' },
      { name: 'dead-list', help: 'list dead-lettered poison jobs' },
      { name: 'requeue', help: 'requeue a dead-lettered job' },
      { name: 'cancel', help: 'cooperatively cancel a job' },
      { name: 'logs', help: 'content-addressed training logs' },
      { name: 'approve', help: 'approve a draft experiment spec' },
      { name: 'rerun', help: 'rerun an approved spec' },
    ],
  },
  {
    name: 'campaign',
    help: 'RU-8 preregistered experiment campaigns',
    subs: [{ name: 'run', help: 'drive a CampaignSpec to a stop rule' }],
  },
  {
    name: 'agent',
    help: 'agent-harness surface',
    subs: [{ name: 'refine', help: 'iterative evidence-gap refinement' }],
  },
  { name: 'probe', help: 'model-route health check', subs: [] },
  { name: 'serve', help: 'start the local API server (headless/SSH entry)', subs: [] },
  { name: 'probe-custom', help: 'health check for user-defined model configs', subs: [] },
  { name: 'memory', help: 'search the re-audit memory queue', subs: [] },
  { name: 'backup', help: 'VACUUM INTO snapshot of the database', subs: [] },
  { name: 'gc', help: 'sweep unreferenced artifact blobs (dry-run by default)', subs: [] },
  { name: 'data', help: 'data footprint', subs: [
    { name: 'info', help: 'runs, db size, artifacts, exports' },
    { name: 'obs', help: 'reliability observability snapshot' },
  ] },
  { name: 'ingest', help: 'deterministic artifact understanding (SDM/dataset profile)', subs: [] },
  { name: 'inspect', help: 'time-travel projection of a run as of an event seq', subs: [] },
  { name: 'verify', help: 'verify a reproducibility bundle', subs: [] },
  { name: 'new', help: 'interactive wizard (TTY only)', subs: [] },
  {
    name: 'completion',
    help: 'print a shell completion script',
    subs: [
      { name: 'bash', help: 'bash script (compgen based)' },
      { name: 'zsh', help: 'zsh script (#compdef based)' },
      { name: 'pwsh', help: 'PowerShell Register-ArgumentCompleter' },
    ],
  },
];

/** Commands that own a sub-level (skip leaves — they have nothing to complete at depth 2). */
const withSubs = (): readonly CompletionCommand[] => FAR_COMMANDS.filter((c) => c.subs.length > 0);

/** Common honest flags across commands (not exhaustive — completion is a convenience, not a parser). */
const COMMON_FLAGS = '--json --help --domain --goal --live --watch';

export const bashCompletion = (): string => {
  const tops = FAR_COMMANDS.map((c) => `'${c.name}'`).join(' ');
  const arrays = withSubs().map((c) => {
    const words = c.subs.map((s) => `'${s.name}'`).join(' ');
    return `  local -a ${c.name}_cmds\n  ${c.name}_cmds=(${words})`;
  }).join('\n');
  const cases = withSubs().map((c) =>
    `    ${c.name}) COMPREPLY=($(compgen -W "\${${c.name}_cmds[*]}" -- "$cur")) ;;`,
  ).join('\n');
  return `# far completion (bash) — generated by \`far completion bash\`; do not edit by hand.
# Install: far completion bash >> ~/.bashrc   (or: eval "$(far completion bash)")
_far() {
  local cur
  cur="\${COMP_WORDS[COMP_CWORD]}"
  local -a far_commands
  far_commands=(${tops})
${arrays}
  if [[ "$cur" == -* ]]; then
    COMPREPLY=($(compgen -W "${COMMON_FLAGS}" -- "$cur"))
    return 0
  fi
  if (( COMP_CWORD == 1 )); then
    COMPREPLY=($(compgen -W "\${far_commands[*]}" -- "$cur"))
    return 0
  fi
  case "\${COMP_WORDS[1]}" in
${cases}
  esac
  return 0
}
complete -F _far far`;
};

export const zshCompletion = (): string => {
  const tops = FAR_COMMANDS.map((c) => `    '${c.name}:${c.help}'`).join('\n');
  const arrays = withSubs().map((c) => {
    const rows = c.subs.map((s) => `    '${s.name}:${s.help}'`).join('\n');
    return `  local -a ${c.name}_cmds\n  ${c.name}_cmds=(\n${rows}\n  )`;
  }).join('\n');
  const cases = withSubs().map((c) =>
    `        ${c.name}) _describe -t far-subcommands '${c.name} subcommand' ${c.name}_cmds ;;`,
  ).join('\n');
  return `#compdef far
# far completion (zsh) — generated by \`far completion zsh\`; do not edit by hand.
# Install: far completion zsh > "\${fpath[1]}/_far"   (after compinit)
_far() {
  local -a far_commands
  far_commands=(
${tops}
  )
${arrays}
  _arguments -C \\
    '--json[machine-readable output: one JSON document on stdout]' \\
    '--help[show help]' \\
    '1:command:->top' \\
    '*::arg:->subcmd'
  case $state in
    top) _describe -t far-commands 'far command' far_commands ;;
    subcmd)
      case $line[1] in
${cases}
      esac
      ;;
  esac
}
_far "$@"`;
};

export const pwshCompletion = (): string => {
  const tops = FAR_COMMANDS.map((c) => `'${c.name}'`).join(', ');
  const cases = withSubs().map((c) => {
    const words = c.subs.map((s) => `'${s.name}'`).join(', ');
    return `    '${c.name}' { @(${words}); break }`;
  }).join('\n');
  return `# far completion (PowerShell) — generated by \`far completion pwsh\`; do not edit by hand.
# Install: append the output of \`far completion pwsh\` to your $PROFILE.
Register-ArgumentCompleter -Native -CommandName 'far' -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $sub = if ($commandAst.CommandElements.Count -gt 1) { $commandAst.CommandElements[1].Value } else { '' }
  $candidates = switch ($sub) {
${cases}
    default { @(${tops}); break }
  }
  $candidates | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
  }
}`;
};

export type SupportedShell = 'bash' | 'zsh' | 'pwsh';

/**
 * Route a shell name to its script. Throws on anything else — main() converts the
 * throw into a usage error (exit 2) so the failure stays visible.
 */
export const completionScript = (shell: string): string => {
  switch (shell) {
    case 'bash': return bashCompletion();
    case 'zsh': return zshCompletion();
    case 'pwsh': return pwshCompletion();
    default: throw new Error(`unsupported shell "${shell}" — supported: bash | zsh | pwsh`);
  }
};
