// src/cli/commands/init.ts
// far init <domain> —— 初始化一个新 DomainPack 脚手架。
//
// 生成对齐项目 claim/FEC 结构的脚手架目录（domain.config.json + claim.template.json + README.md），
// 供用户填充后接入 far ask / court / arena / fec compile。
// 诚实边界：本命令生成的是「结构化模板」（非可执行的 domain 注册表 —— DomainPackRegistry 是 V2 路线）；
// 它降低新 domain 的接入成本，但不自动接线 src/ pipeline。

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

export interface InitArgs {
  readonly domain: string;
  readonly outDir: string;
  readonly force: boolean;
}

export function parseInitArgs(argv: readonly string[]): InitArgs {
  let domain = '';
  let outDir = '';
  let force = false;

  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === undefined) continue;
    if (a === '--out') {
      outDir = argv[++i] ?? '';
      continue;
    }
    if (a === '--force') {
      force = true;
      continue;
    }
    if (a.startsWith('--')) {
      throw new Error(`far init: unknown argument "${a}"`);
    }
    if (domain === '') {
      domain = a;
    }
  }

  if (domain === '') {
    throw new Error('far init: missing <domain> name (e.g. astro / mmlu / bio)');
  }
  if (outDir === '') {
    outDir = resolve(`./domains/${domain}`);
  }

  return { domain, outDir, force };
}

function domainClassTag(domain: string): string {
  const upper = domain.replace(/[^a-zA-Z0-9]/g, '-').toUpperCase();
  return upper.length > 0 ? upper : 'DOMAIN';
}

function buildFiles(args: InitArgs): ReadonlyArray<readonly [string, string]> {
  const tag = domainClassTag(args.domain);
  const createdAt = new Date().toISOString();
  const claimId = `${tag}-0001`;

  const config = {
    schemaVersion: 'far.domain_pack.v1',
    name: args.domain,
    claimClass: tag,
    claimIdPrefix: tag,
    createdAt,
    description: 'FAR-Chain DomainPack scaffold — fill it in, then connect to far ask/court/arena',
    wiring: {
      ask: `far ask "<question>" --profile offline_replay`,
      fec: `far fec compile --claim fec.template.json --out <outdir>`,
      court: `far court "<claim>"`,
    },
  };

  const claimTemplate = {
    claimId,
    claimText: '<enter a falsifiable scientific claim here>',
    claimClass: tag,
    falsificationSpec: {
      prediction: '<falsifiable prediction: if X holds, Y should be observed>',
      metric: '<measurement metric name>',
      comparator: 'gt',
      falsificationThreshold: 0,
    },
    sourceAnchor: {
      type: '<dataset | paper | model>',
      identifier: '<DOI / arXiv / accession / model name>',
    },
    limitations: ['scaffold placeholder until filled in; not a real scientific claim'],
  };

  const readme = `# DomainPack: ${args.domain}

Generated by \`far init ${args.domain}\` (${createdAt}).

## Structure
- \`domain.config.json\` — domain metadata + wiring guide
- \`claim.template.json\` — falsifiable claim template (fill in claimText / falsificationSpec / sourceAnchor)

## Onboarding steps
1. Edit \`claim.template.json\` — fill in the real falsifiable claim and measurement spec.
2. Edit \`fec.template.json\` — fill in the measurement spec and statistical plan (the template contains <placeholders>; until filled in,\n   \`far fec compile --claim fec.template.json --out <outdir>\` reports the specific missing fields, e.g. METRIC_MISSING).
3. \`far ask "<a question based on this claim>"\` — run the 6-stage FSM (offline_replay).
4. \`far court "<claim>"\` / \`far arena "<hypothesis>"\` — multi-model court / adversarial arena.

## Boundaries
This scaffold is a structured template, **not an executable domain registry** (DomainPackRegistry is on the V2 roadmap).
The verdict is still produced by the deterministic R0-R9 kernel (the LLM is not the adjudicator); real inference needs \`--profile\` against a real provider.

`;

  const fecTemplate = {
    fecId: `FEC-${tag}-0001`,
    contractVersion: 'FEC/2.0',
    claimId,
    measurableImplication: '<falsifiable measurable implication: if the claim holds, the metric should reach the threshold>',
    scope: {
      population: '<applicable population / dataset>',
      timeWindow: '<time window>',
      domainConstraint: '<domain constraint / falsification method>',
    },
    requiredEvidence: [
      {
        evidenceId: `${tag}-primary-evidence`,
        kind: 'measurement',
        critical: true,
        description: '<key evidence supporting the claim>',
        verificationCheckId: `${tag}-check-1`,
      },
    ],
    datasetRequirements: [
      {
        name: '<dataset name>',
        contentHashAlgorithm: 'sha256',
        allowSynthetic: false,
        schemaFingerprintRequired: false,
      },
    ],
    workflowRequirements: [
      {
        name: '<reproduction workflow>',
        engine: 'manual',
        requireContainerDigest: false,
        requireCommandHash: false,
        expectedNetworkPolicy: 'off',
        requireFixedSeed: false,
      },
    ],
    metric: {
      metricKey: '<metric_key>',
      description: '<metric description>',
      unit: '<unit>',
      computationRef: '<computation reference>',
      isDeterministic: true,
    },
    threshold: {
      value: 0,
      unit: '<unit>',
      thresholdSemantics: 'gt',
      preregistered: false,
    },
    direction: 'greater',
    statisticalPlan: {
      primaryMetric: '<metric_key>',
      nullHypothesis: '<H0: metric <= threshold>',
      alternativeHypothesis: '<H1: metric > threshold>',
      alpha: 0.05,
      effectDirection: 'greater',
      confidenceIntervalMethod: 'not_provided',
      multipleTestingCorrection: 'none',
      missingDataPolicy: 'not_provided',
      outlierPolicy: 'not_provided',
      stoppingRule: 'not_provided',
    },
    seedPolicy: { fixed: false, allowCherryPick: false, justification: '<seed policy description>' },
    deviationPolicy: {
      criticalCategories: ['metric_swap', 'alpha_rewrite'],
      nonCriticalHandling: 'degrade',
      requireExplicitLog: true,
    },
    freeze: {
      fecHash: '0'.repeat(64),
      actor: { actorKind: 'deterministic_freezer', actorId: `${tag}-init` },
      timestamp: createdAt,
      environmentPolicy: '<environment lock policy>',
      deviationPolicyHash: '0'.repeat(64),
      frozenBy: 'deterministic_freezer',
    },
    integrityFlags: [],
  };

  return [
    ['domain.config.json', `${JSON.stringify(config, null, 2)}\n`],
    ['claim.template.json', `${JSON.stringify(claimTemplate, null, 2)}\n`],
    ['fec.template.json', `${JSON.stringify(fecTemplate, null, 2)}\n`],
    ['README.md', readme],
  ];
}

export function runInit(argv: readonly string[]): number {
  let args: InitArgs;
  try {
    args = parseInitArgs(argv);
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    process.stderr.write(`${msg}\n  usage: far init <domain> [--out <dir>] [--force]\n`);
    return 2;
  }


  if (existsSync(args.outDir) && !args.force) {
    process.stderr.write(
      `far init: directory already exists at ${args.outDir} (use --force to overwrite)\n`,
    );
    return 2;
  }

  mkdirSync(args.outDir, { recursive: true });
  const files = buildFiles(args);
  for (const [name, content] of files) {
    writeFileSync(resolve(args.outDir, name), content, 'utf8');
  }

  process.stdout.write('\n  FAR-Chain · far init (DomainPack scaffold)\n');
  process.stdout.write('  ─────────────────────────────────────────────────\n');
  process.stdout.write(`  domain   : ${args.domain}（claimClass=${domainClassTag(args.domain)}）\n`);
  process.stdout.write(`  output   : ${args.outDir}\n`);
  process.stdout.write(`  files    : ${files.map((f) => f[0]).join(', ')}\n`);
  process.stdout.write('  ─────────────────────────────────────────────────\n');
  process.stdout.write('  next: edit claim.template.json → far fec compile --claim <path>\n\n');
  return 0;
}
